### ISSUE TITLE
NICK 설정 없이 서버 연결 시 nickname 설정

### ISSUE THREAD

**Issue by Newsujin** [InfpRC/INFPRC#14]

**Comment by hyeongsh** [comment]
nick 설정 없이 서버 연결 불가능
-> nick, user, pass 전부 받아야만 접속할 수 있게 설정해야 함.

**Comment by hyeongsh** [comment]
nickname 중복의 경우 닉네임 대신 * 을 찍어서 넣어주면 irssi가 _를 자동으로 붙여준다.
하지만 닉네임_ 까지 존재할 경우에는 더이상 자동으로 지원해주지 못하고 원래 닉네임으로 접속해버린다

**Comment by hyeongsh** [comment]
nickname 변경 시 같은 이름은 프로토콜 메시지를 전송하지 않음
