### ISSUE TITLE
JOIN 시 참가자 명단 전송 수정

### ISSUE THREAD

**Issue by hyeongsh** [InfpRC/INFPRC#43]
- 참가자 명단을 일정 수만큼만 보여주고 잘라야함
- 종료는 list end 표시를 통해 종료시켜야 함

**Comment by Newsujin** [comment]
- 512 byte를 넘을 경우 `\r\n` 이후의 참가자 명단을 buffer에 다시 담아서 전송
- 클라이언트가 `sendBuf()`할 때, size()를 개행까지로 설정
