### ISSUE TITLE
QUIT 명령어 실행 시 개인 채팅방에도 메시지 전송

### ISSUE THREAD

**Issue by Newsujin** [InfpRC/INFPRC#59]

**Comment by Newsujin** [comment]
client에 개인 채팅방 이력을 저장할 필드를 생성해야 할 것 같습니다..

**Comment by KRimwoo** [comment]
(절망) 상대가 닉네임을 바꿔도 유효해야 하나요? 닉네임들을 가지고 있어야하는지 fd 값을 가지고 있어야 하는지 궁금합니다...
modern irc 보면 ["This is typically only dispatched to clients that share a channel with the exiting user." ](https://modern.ircdocs.horse/#quit-message) 라고 되어있는데 필수는 아닐 것 같아요

**Comment by Newsujin** [comment]
> (절망) 상대가 닉네임을 바꿔도 유효해야 하나요? 닉네임들을 가지고 있어야하는지 fd 값을 가지고 있어야 하는지 궁금합니다... modern irc 보면 ["This is typically only dispatched to clients that share a channel with the exiting user." ](https://modern.ircdocs.horse/#quit-message) 라고 되어있는데 필수는 아닐 것 같아요

오 modern irc에 해당 내용이 있었군요 정말 다행입니다 ㅎㅎ 그러면 필수가 아니니 이슈 close 하겠습니다!
